// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksxfvyeiwhxeoligzqpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzeGZ2eWVpd2h4ZW9saWd6cXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzAyNDgsImV4cCI6MjA3MDk0NjI0OH0.ZZW7MrHpJ688evGUG25ros-GhVQi2ALdb9efhmF1V-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});